version: "3.7"

services:
  mongo:
    image: mongo
    container_name: database_mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=moneydb

  app:
    build: .
    container_name: money-api
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - mongo
    depends_on:
      - mongo
